steps:
- name: gcr.io/cloud-builders/gcloud
  args: ['compute', 'ssh', '${_USER}@${_INSTANCE}', '--zone', '${_ZONE}', '--command', 'cd Bucket.js/src; git pull; npm i; forever stop 0; forever start main.js; exit']
