steps:
- name: gcr.io/cloud-builders/gcloud
  args: ['compute', 'ssh', '${_USER}@${_INSTANCE}', '--zone', '${_ZONE}', '--command', 'forever stop 0; cd Bucket.js; git fetch; git reset --hard origin/master; npm i; cd src; forever start main.js; exit']
